# Generated by Django 2.0.5 on 2018-06-14 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=60)),
                ('id_no', models.SlugField(max_length=11, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, default='default_patient_img.png', upload_to='')),
                ('history', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
